### PR TITLE
Add Cython Support

### PR DESCRIPTION
**Pull request by Theelgirl**

### CODE REVIEW

**Comment by AlfredoSequeida** [comment]
So, this is my first time trying a Cython and I figure the package installation would be the same, but when I try to install using pip, this is what I get: 

**ERROR: More than one .egg-info directory found in /tmp/pip-pip-egg-info-d3jh1vfk**

any ideas?

**Comment by Theelgirl** [comment]
@AlfredoSequeida I think it means you have some sort of corrupt Cython install from before. Try doing ``pip install cython==3.0a6``, or check out possible solutions here:
https://github.com/pypa/pip/issues/8201

**Comment by Theelgirl** [comment]
Added the cythonizer.py script in #21. Once cython is installed, if setup.py doesn't immediately install for you, you can run ``python3 cythonizer.py build_ext --inplace`` to install the module.

**Comment by Theelgirl** [comment]
Closing in favor of #21

**Pull request closed without merging**
