### PR TITLE
Added requirements.txt, fixed output file naming issue

### LINKED ISSUE #5: Add requirements.txt
There should be a `requirements.txt` file as well as a "Dependendies" section in the Readme (#4) to make usage easier (rather than guessing from the code which packages/libraries to install).

### LINKED ISSUE #8: [Bug] Output file on decoding is always "file.bin"
Whenever I run this script to decode a video it generated, the output file is `file.bin`. I tried renaming the extension to match the original file I encoded but it didn't work. Morevover, this `file.bin` is lighter than the original file.

### PR DESCRIPTION
**Pull request by dtaivpp**
Fixed #8 - Output file path wasnt being passed in. Updated input file path logic to reflect. 
Tested:
- Default for encoding
- With output flag for encoding
- Defualt for decoding
- With output flag for decoding

Fixed #5 - Added requirements.txt

### CODE REVIEW

**Comment by dtaivpp** [comment]
Screen Shot 2020-10-07 at 10 18 32 AM

**Comment by dtaivpp** [comment]
@AlfredoSequeida pinging you because you are committing way to fast for me to keep up lol

**Comment by AlfredoSequeida** [comment]
@dtaivpp Haha sorry, I am a little limited on time, so I haven't seen any of the commits yet. I am done with my changes. Respond when you are ready and I will check out the changes. Also thank you for being so active, it really helps.

**Comment by dtaivpp** [comment]
@AlfredoSequeida All good mate, I was really just harrassing you for kicks because I kept seeing you committing. Either way, I added a requirements.txt file here, but I can abandon this and remove if we want to go with just a setup.py. I have seen some repo's with both because developers tend to like them for virtual environments but up to you.

**Comment by dtaivpp** [comment]
@AlfredoSequeida  just kidding just deleted it without needing to do a new PR. This is ready to ship

**Comment by AlfredoSequeida** [comment]
It looks good with the exception of a typo on like 121

file_path should be filepath, I think after that fix it should be good to merge.

**Comment by dtaivpp** [comment]
@AlfredoSequeida line 121 is correct. filepath there is the new variable for storing the filepath not the parameter.

**Comment by AlfredoSequeida** [comment]
Sorry for the wait, the issue is that file_path is undefined, so for example if you try to run something like:

`fvid -i video.mp4 -d -o text.txt`

you should see that file_name is undefned, what what I figured you were trying to do is check if the 

`filepath == None`

and if you decide to change file_path to filepath, the same has to be done for like 124:

`filepath = file_path`

since at that point in the current state, file_path is also undefined.

**Comment by dtaivpp** [comment]
@AlfredoSequeida oh man I see what you are saying. I was being dense because I thought I had the file_path defined in the function heading. Fixing that now and then it should be ready.

**Comment by AlfredoSequeida** [comment]
@dtaivpp This looks great! Thank you!

**Pull request merged**
